{% set name = "mpire" %}
{% set version = "2.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mpire-{{ version }}.tar.gz
  sha256: 8244a2e8f9aeacd8b13e79af590f2c085a9ce2ea2dca92ce4f82a291a280991f

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - tqdm
    - dataclasses
    - pywin32  # [win]

test:
  imports:
    - mpire
    - mpire.dashboard

about:
  home: https://github.com/Slimmer-AI/mpire
  summary: A Python package for easy multiprocessing, but faster than multiprocessing
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - synapticarbors
