{% set name = "mpire" %}
{% set version = "2.7.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mpire-{{ version }}.tar.gz
  sha256: 6ffe7ce92d4b40fcf35d73ebaadf76455d11e4a2c923ef0c9f25b6c885bf5d0f

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - tqdm >=4.27
    - dataclasses
    - pywin32  # [win]
    - pygments >=2.0

test:
  imports:
    - mpire
    - mpire.dashboard
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/Slimmer-AI/mpire
  summary: A Python package for easy multiprocessing, but faster than multiprocessing
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - synapticarbors
