{% set name = "mpire" %}
{% set version = "2.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mpire-{{ version }}.tar.gz
  sha256: 907051a4095779104eddcf5dae37e9d263778d8a51d4acec3e6354f5d45c933c

build:
  number: 2
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - tqdm >=4.27
    - dataclasses
    - pywin32  # [win]
    - pygments >=2.0

test:
  imports:
    - mpire
    - mpire.dashboard
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/Slimmer-AI/mpire
  summary: A Python package for easy multiprocessing, but faster than multiprocessing
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - synapticarbors
