{% set name = "mpire" %}
{% set version = "2.10.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mpire-{{ version }}.tar.gz
  sha256: 8a1c510a159867d0c0d66b9ce360b835268f9ba3bfe654f59fae9e8ca6c221bd

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - tqdm >=4.27
    - pywin32-on-windows
    - pygments >=2.0

test:
  imports:
    - mpire
    - mpire.dashboard
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/sybrenjansen/mpire
  summary: A Python package for easy multiprocessing, but faster than multiprocessing
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - synapticarbors
