{% set name = "mpire" %}
{% set version = "2.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mpire-{{ version }}.tar.gz
  sha256: 695793ad0cc4e4e62e30b0af49602cec4eddd06faeb5aca8bf01755e73479286

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - tqdm
    - pywin32  # [win]

test:
  imports:
    - mpire
    - mpire.dashboard

about:
  home: https://github.com/Slimmer-AI/mpire
  summary: A Python package for easy multiprocessing, but faster than multiprocessing
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - synapticarbors
