{% set name = "mpire" %}
{% set version = "2.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mpire-{{ version }}.tar.gz
  sha256: 67933fbb85ca73655055a3eb9c16905884505a4dc4d8842a44214b8a7748dd65

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - tqdm
    - dataclasses
    - pywin32  # [win]

test:
  imports:
    - mpire
    - mpire.dashboard

about:
  home: https://github.com/Slimmer-AI/mpire
  summary: A Python package for easy multiprocessing, but faster than multiprocessing
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - synapticarbors
