{% set name = "mpire" %}
{% set version = "2.10.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mpire-{{ version }}.tar.gz
  sha256: 029d2d3ef7de4e04866f76ca9141ec4e8bf0d39b5a1128289c85e04257613ccd

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - tqdm >=4.27
    - pywin32-on-windows >=301
    - pygments >=2.0

test:
  imports:
    - mpire
    - mpire.dashboard
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/sybrenjansen/mpire
  summary: A Python package for easy multiprocessing, but faster than multiprocessing
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - synapticarbors
